"""primeiro

Revision ID: 14d0c924bed0
Revises: 
Create Date: 2023-06-02 17:38:48.554678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14d0c924bed0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usuarios_id', table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index('ix_usuario_id', table_name='usuario')
    op.drop_table('usuario')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('senha', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usuario_id', 'usuario', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('nome', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('senha', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usuarios_id', 'usuarios', ['id'], unique=False)
    # ### end Alembic commands ###
